# Generated by Django 4.0.4 on 2022-05-06 13:03

from django.db import migrations, models

def create_data(apps, schema_editor):
    Movie = apps.get_model('movies', 'Movie')
    Student(movie_name="Joe Silver", movie_genre="FNAC").save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('movie_genre', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['movie_genre'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('movies', models.ManyToManyField(to='recommended.movie')),
            ],
        ),
        migrations.RunPython(create_data),
    ]
