# Generated by Django 4.0.4 on 2022-05-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('adult', models.TextField(blank=True, null=True)),
                ('belongs_to_collection', models.TextField(blank=True, null=True)),
                ('budget', models.TextField(blank=True, null=True)),
                ('genres', models.TextField(blank=True, null=True)),
                ('homepage', models.TextField(blank=True, null=True)),
                ('imdb_id', models.TextField(blank=True, null=True)),
                ('original_language', models.TextField(blank=True, null=True)),
                ('original_title', models.TextField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('popularity', models.TextField(blank=True, null=True)),
                ('poster_path', models.TextField(blank=True, null=True)),
                ('production_companies', models.TextField(blank=True, null=True)),
                ('production_countries', models.TextField(blank=True, null=True)),
                ('release_date', models.TextField(blank=True, null=True)),
                ('revenue', models.TextField(blank=True, null=True)),
                ('runtime', models.TextField(blank=True, null=True)),
                ('spoken_languages', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('tagline', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('video', models.TextField(blank=True, null=True)),
                ('vote_average', models.TextField(blank=True, null=True)),
                ('vote_count', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('cast', models.TextField(blank=True, null=True)),
                ('cast_size', models.TextField(blank=True, null=True)),
                ('crew_size', models.TextField(blank=True, null=True)),
                ('director', models.TextField(blank=True, null=True)),
                ('castkey', models.TextField(blank=True, null=True)),
                ('score', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movies',
                'managed': False,
            },
        ),
    ]
